CLEANUP_COMMANDS = {
    "ansible_ansible": [
        "rm -rf .azure-pipelines",
        "rm -rf .claude",
        "rm -rf .github",
        "rm -rf changelogs",
        "rm -rf licenses",
        "find . -name \"*.md\" -delete",
        "rm -rf lib/ansible/keyword_desc.yml",
    ],
    "getzep_graphiti": [
        "rm -rf .github",
        "rm -rf examples",
        "rm -rf images",
        "find . -name \"*.md\" -delete",
        "rm -rf Dockerfile",
        "rm -rf Makefile",
        "rm -rf docker-compose.test.yml",
        "rm -rf docker-compose.yml",
        "rm -rf ellipsis.yml",
        "rm -rf uv.lock",
    ],
    "huggingface_smolagents": [
        "rm -rf .github",
        "find . -name \"*.md\" -delete",
        "rm -rf docs",
        "rm -rf examples",
        "rm -rf Makefile",
    ],
    "huggingface_transformers": [
        "rm -rf .github",
        "find . -name \"*.md\" -delete",
        "rm -rf .circleci",
        "rm -rf docs",
        "rm -rf examples",
        "rm -rf notebooks",
        "rm -rf Makefile",
    ],
    "jlowin_fastmcp": [
        "rm -rf .claude",
        "rm -rf .cursor",
        "rm -rf .github",
        "rm -rf docs",
        "find . -name \"*.md\" -delete",
        "rm -rf examples",
        "rm -rf uv.lock",
    ],
    "openai_openai-agents-python": [
        "rm -rf .codex",
        "rm -rf .github",
        "rm -rf .vscode",
        "find . -name \"*.md\" -delete",
        "rm -rf docs",
        "rm -rf examples",
        "rm -rf Makefile",
        "rm -rf uv.lock",
    ],
    "opshin_opshin": [
        "rm -rf .github",
        "rm -rf docs",
        "find . -name \"*.md\" -delete",
        "rm -rf examples",
        "rm -rf build_docs.sh",
        "rm -rf uv.lock",
    ],
    "pdm-project_pdm": [
        "rm -rf .github",
        "find . -name \"*.md\" -delete",
        "rm -rf docs",
        "rm -rf news",
        "rm -rf mkdocs.yml",
    ],
    "qodo-ai_pr-agent": [
        "rm -rf .github",
        "rm -rf docker",
        "find . -name \"*.md\" -delete",
        "rm -rf docs",
        "rm -rf github_action",
        "rm -rf Dockerfile.github_action",
        "rm -rf Dockerfile.github_action_dockerhub",
    ],
    "tinygrad_tinygrad": [
        "rm -rf .github",
        "find . -name \"*.md\" -delete",
        "rm -rf docs",
        "rm -rf examples",
    ],
    "vibrantlabsai_ragas": [
        "rm -rf .github",
        "find . -name \"*.md\" -delete",
        "rm -rf .cursor",
        "rm -rf .claude",
        "rm -rf docs",
        "rm -rf examples",
        "rm -rf Makefile",
    ],
    "wagtail_wagtail": [
        "rm -rf .github",
        "find . -name \"*.md\" -delete",
        "rm -rf .circleci",
        "rm -rf .tx",
        "rm -rf docs",
        "rm -rf Makefile",
    ],
}
