"""Dependency-free SVG outcome matrices for the two variance pilots."""

from __future__ import annotations

import csv
import html
import json
import re
import subprocess
from pathlib import Path

from .io import REPO_ROOT


EXPECTED_TASKS = 10
EXPECTED_REPETITIONS = 20
ALLOWED_CATEGORIES = {"solved", "failed_patch", "empty_patch", "no_action", "timeout"}
FONT = "'Helvetica Neue', Helvetica, Arial, sans-serif"


def load_palette(path: Path) -> dict[str, str]:
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    return {name: value["hex"] for name, value in data["roles"].items()}


def load_matrix(path: Path) -> tuple[list[str], dict[tuple[str, int], str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    matrix: dict[tuple[str, int], str] = {}
    tasks = sorted({row["task"] for row in rows})
    if len(tasks) != EXPECTED_TASKS:
        raise ValueError(f"Expected {EXPECTED_TASKS} pilot tasks, found {len(tasks)}")
    for row in rows:
        match = re.fullmatch(r"run_(\d+)", row["repetition"])
        if not match:
            raise ValueError(f"Unexpected repetition label: {row['repetition']}")
        repetition = int(match.group(1))
        category = row["category"]
        if category not in ALLOWED_CATEGORIES:
            raise ValueError(f"Pilot figure cannot display category: {category}")
        key = (row["task"], repetition)
        if key in matrix:
            raise ValueError(f"Duplicate pilot row: {key}")
        matrix[key] = category
    expected = {(task, repetition) for task in tasks for repetition in range(EXPECTED_REPETITIONS)}
    missing = expected - matrix.keys()
    additional = matrix.keys() - expected
    if missing or additional:
        raise ValueError(
            f"Pilot matrix is incomplete: {len(missing)} missing and {len(additional)} additional rows"
        )
    return tasks, matrix


def task_label(task: str) -> str:
    label = task.split("_", 1)[1] if "_" in task else task
    return label.replace("openai-agents-python", "agents-python")


def rect(x: float, y: float, width: float, height: float, fill: str, *,
         radius: float = 0, stroke: str | None = None, stroke_width: float = 0) -> str:
    border = f' stroke="{stroke}" stroke-width="{stroke_width}"' if stroke else ""
    return (
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{width:.1f}" height="{height:.1f}" '
        f'rx="{radius}" fill="{fill}"{border}/>'
    )


def text(x: float, y: float, value: str, size: float, color: str, *,
         anchor: str = "start", weight: str | None = None) -> str:
    font_weight = f' font-weight="{weight}"' if weight else ""
    return (
        f'<text x="{x:.1f}" y="{y:.1f}" font-size="{size}" fill="{color}" '
        f'text-anchor="{anchor}"{font_weight}>{html.escape(value)}</text>'
    )


def line(x1: float, y1: float, x2: float, y2: float, color: str, width: float = 1) -> str:
    return (
        f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
        f'stroke="{color}" stroke-width="{width}" stroke-linecap="round"/>'
    )


def generate_matrix_svg(
    raw_mapping: Path,
    palette_path: Path,
    output_path: Path,
    series_role: str,
    fill_role: str,
) -> None:
    tasks, matrix = load_matrix(raw_mapping)
    palette = load_palette(palette_path)
    series = palette[series_role]
    series_fill = palette[fill_role]
    paper = palette["paper"]
    ink = palette["ink"]
    secondary = palette["ink-secondary"]
    muted = palette["ink-muted"]
    hairline = palette["hairline"]
    rule = palette["rule"]

    tile_width, tile_height = 30, 24
    x0, y0 = 230, 70
    width = 960
    height = y0 + len(tasks) * tile_height + 105
    try:
        source = raw_mapping.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        source = raw_mapping.as_posix()
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'font-family="{FONT}">',
        f'  <metadata>Generated by thesis-results-assets from {html.escape(source)}</metadata>',
        "  " + rect(0, 0, width, height, paper),
        "  " + text(x0 - 10, y0 - 18, "Task", 13, ink, anchor="end", weight="600"),
        "  " + text(x0 + 300, y0 - 18, "Repetition j", 13, ink, anchor="middle", weight="600"),
        "  " + text(x0 + 616, y0 - 18, "Solved of 20", 13, ink, weight="600"),
        "  " + line(x0 - 205, y0 - 8, x0 + 710, y0 - 8, rule),
    ]

    for task_index, task in enumerate(tasks):
        y = y0 + task_index * tile_height
        parts.append("  " + text(x0 - 10, y + tile_height - 7, task_label(task), 12, secondary, anchor="end"))
        solved = 0
        for repetition in range(EXPECTED_REPETITIONS):
            category = matrix[(task, repetition)]
            x = x0 + repetition * tile_width
            if category == "solved":
                solved += 1
                parts.append("  " + rect(x + 2, y + 2, 26, 20, series, radius=3))
            elif category == "failed_patch":
                parts.append("  " + rect(x + 2, y + 2, 26, 20, series_fill, radius=3))
            elif category == "timeout":
                parts.append("  " + rect(x + 2, y + 2, 26, 20, series_fill, radius=3))
                parts.append("  " + line(x + 7, y + 17, x + 23, y + 7, series, 1.6))
            elif category == "empty_patch":
                parts.append("  " + rect(x + 2, y + 2, 26, 20, hairline, radius=3))
            elif category == "no_action":
                parts.append("  " + rect(x + 2.5, y + 2.5, 25, 19, paper, radius=3, stroke=rule, stroke_width=1.2))
        parts.append("  " + text(x0 + 616, y + tile_height - 7, str(solved), 12, ink))

    matrix_end = y0 + len(tasks) * tile_height
    parts.append("  " + line(x0 - 205, matrix_end + 4, x0 + 710, matrix_end + 4, rule))
    for repetition in (0, 4, 9, 14, 19):
        parts.append(
            "  " + text(x0 + repetition * tile_width + 15, matrix_end + 20, str(repetition + 1), 11, muted, anchor="middle")
        )

    legend = [
        ("solved", "solved"),
        ("failed patch", "failed_patch"),
        ("timeout", "timeout"),
        ("empty patch", "empty_patch"),
        ("no action", "no_action"),
    ]
    x, y = 125, matrix_end + 58
    spacings = {"solved": 105, "failed patch": 140, "timeout": 115, "empty patch": 135, "no action": 120}
    for label, category in legend:
        if category == "solved":
            parts.append("  " + rect(x, y - 11, 16, 14, series, radius=3))
        elif category == "failed_patch":
            parts.append("  " + rect(x, y - 11, 16, 14, series_fill, radius=3))
        elif category == "timeout":
            parts.append("  " + rect(x, y - 11, 16, 14, series_fill, radius=3))
            parts.append("  " + line(x + 3, y + 1, x + 13, y - 9, series, 1.6))
        elif category == "empty_patch":
            parts.append("  " + rect(x, y - 11, 16, 14, hairline, radius=3))
        else:
            parts.append("  " + rect(x, y - 11, 16, 14, paper, radius=3, stroke=rule, stroke_width=1.2))
        parts.append("  " + text(x + 22, y, label, 11.5, secondary))
        x += spacings[label]

    parts.append("</svg>")
    output_path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def render_svg(svg_path: Path) -> None:
    base = svg_path.with_suffix("")
    subprocess.run(
        ["rsvg-convert", "-f", "pdf", "-o", str(base.with_suffix(".pdf")), str(svg_path)],
        check=True,
    )
    subprocess.run(
        ["rsvg-convert", "-f", "png", "--zoom", "2", "-o", str(base) + "@2x.png", str(svg_path)],
        check=True,
    )
