"""Generate reviewable thesis assets from versioned analysis outputs."""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Any

from .pilot_figures import generate_matrix_svg, render_svg
from .behaviour import summarize_behaviour
from .result_figures import (
    generate_outcome_composition_svg,
    generate_pairwise_disagreement_svg,
    generate_pass1_forest_svg,
    generate_mean_effort_forest_svg,
    generate_phase_profile_svg,
)


ROLE_LABELS = {
    "initial_main_run_repetition_choice": "Initial choice of repetition count $n$",
    "transfer_check_only": "Transfer and runtime check only",
}

CELL_ORDER = ("K0", "K0d", "K1", "K1s", "K2", "K2s")
CONTRAST_ORDER = (
    "K1-K0",
    "K2-K0",
    "K1s-K1",
    "K2s-K2",
    "K0d-K0",
    "K1-K0d",
    "K2-K0d",
)
RQ_CONTRASTS = {
    "RQ1": ("K1-K0", "K2-K0"),
    "RQ2": ("K1s-K1", "K2s-K2"),
    "RQ3": ("K0d-K0", "K1-K0d", "K2-K0d"),
}
OUTCOME_CATEGORIES = {
    "solved",
    "failed_patch",
    "empty_patch",
    "no_action",
    "timeout",
    "evaluation_error",
    "serving_error",
    "missing_artifact",
}
KNOWLEDGE_CATEGORIES = ("P", "D", "N", "M")


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def display_path(path: Path) -> str:
    try:
        return path.relative_to(Path.cwd()).as_posix()
    except ValueError:
        return path.as_posix()


def source_comment(command: str, sources: list[Path]) -> str:
    source_lines = "\n".join(f"% Source: {display_path(path)}" for path in sources)
    return f"% Generated by: {command}\n{source_lines}\n"


def context_categorization_table(
    statement_rows: list[dict[str, str]], provenance: str
) -> str:
    """Render repository-level statement counts from the reviewed categorization."""
    per_repository: dict[str, Counter[str]] = {}
    identifiers: set[str] = set()
    for row in statement_rows:
        identifier = row.get("id", "")
        repository = row.get("repo", "")
        category = row.get("bucket", "")
        if not identifier or not repository:
            raise ValueError("Every context statement requires an id and repository")
        if identifier in identifiers:
            raise ValueError(f"Duplicate context-statement id: {identifier}")
        identifiers.add(identifier)
        if category not in KNOWLEDGE_CATEGORIES:
            raise ValueError(f"Unknown context-statement category: {category}")
        per_repository.setdefault(repository, Counter())[category] += 1

    def display_name(repository: str) -> str:
        name = repository.rsplit("/", 1)[-1]
        return "openai-agents" if name == "openai-agents-python" else name

    ordered = sorted(
        per_repository.items(),
        key=lambda item: (-sum(item[1].values()), display_name(item[0]).lower()),
    )
    totals: Counter[str] = Counter()
    rendered: list[str] = []
    for index, (repository, counts) in enumerate(ordered):
        totals.update(counts)
        values = []
        for category in KNOWLEDGE_CATEGORIES:
            value = counts[category]
            values.append(
                r"\textbf{0}" if category in {"P", "D"} and value == 0 else str(value)
            )
        line = " & ".join(
            [display_name(repository), *values, str(sum(counts.values()))]
        ) + r" \\"
        rendered.append((r"\rowcolor{black!6} " if index % 2 else "") + line)

    total_values = [str(totals[category]) for category in KNOWLEDGE_CATEGORIES]
    rendered.append(
        " & ".join(
            [
                r"\textbf{Total}",
                *(rf"\textbf{{{value}}}" for value in total_values),
                rf"\textbf{{{sum(totals.values())}}}",
            ]
        )
        + r" \\"
    )
    return (
        provenance
        + "\\begin{tabular}{@{}lrrrrr@{}}\n"
        + "  \\toprule\n"
        + "  Repository & \\multicolumn{4}{c}{Statement category} & Total \\\\\n"
        + "  \\cmidrule(lr){2-5}\n"
        + "   & Procedural & Descriptive & Normative & Meta & \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered[:-1])
        + "\n  \\midrule\n  "
        + rendered[-1]
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def percent(value: float) -> str:
    return f"{100 * value:.1f}\\,\\%"


def fixed(value: str | float, places: int = 2) -> str:
    quantum = Decimal(1).scaleb(-places)
    return str(Decimal(str(value)).quantize(quantum, rounding=ROUND_HALF_UP))


def signed(value: str | float, places: int = 1, scale: float = 1.0) -> str:
    number = float(value) * scale
    if abs(number) < 0.5 * 10 ** (-places):
        number = 0.0
    return f"{number:+.{places}f}"


def p_value(value: str | float) -> str:
    number = float(value)
    return "$<.001$" if number < 0.001 else f"{number:.3f}"


def contrast_tex(value: str) -> str:
    return value.replace("-", "$-$")


def pass1_result_table(
    glm_rows: list[dict[str, str]],
    qwen_rows: list[dict[str, str]],
    family: str,
    provenance: str,
) -> str:
    by_configuration = {
        "$g_{\\mathrm{GLM}}$": {row["contrast"]: row for row in glm_rows},
        "$g_{\\mathrm{Qwen}}$": {row["contrast"]: row for row in qwen_rows},
    }
    rendered: list[str] = []
    for contrast in RQ_CONTRASTS[family]:
        for configuration, rows in by_configuration.items():
            row = rows[contrast]
            decision = "evidence" if row["holm_reject_alpha_0_05"] == "True" else "not established"
            line = " & ".join(
                [
                    configuration,
                    contrast_tex(contrast),
                    row["n_tasks"],
                    f"{signed(row['effect'], scale=100)}",
                    fixed(100 * float(row['standard_error'])),
                    f"[{signed(row['ci_low'], scale=100)}, {signed(row['ci_high'], scale=100)}]",
                    f"{float(row['t_value']):+.2f} ({row['degrees_freedom']})",
                    p_value(row["p_value"]),
                    p_value(row["p_value_holm"]),
                    decision,
                ]
            ) + r" \\"
            rendered.append((r"\rowcolor{black!6} " if len(rendered) % 2 else "") + line)
    return (
        provenance
        + "\\begin{tabular}{@{}llrrrrrrrl@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & Contrast & $|T^{(g)}_{ab}|$ & $\\widehat\\Delta$ & $\\mathrm{SE}(\\widehat\\Delta)$ & 95\\,\\% CI & "
          "$t$ (df) & $p$ & $p^{\\mathrm{Holm}}$ & Evidence \\\\\n"
        + "   & & & [pp] & [pp] & [pp] & & & & \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def _effort_by_contrast(data: dict[str, Any]) -> dict[str, dict[str, Any]]:
    if data.get("estimator") != "mean_effort_per_measurable_run":
        raise ValueError("Mean-effort tables require v3 mean-effort outputs, not historical solved-run ratios")
    return {row["contrast"]: row for row in data["contrasts"]}


def _effort_cell(metric: dict[str, Any], unit: str) -> tuple[str, str, str, str]:
    divisor = 1000.0 if unit == "tokens" else 1.0
    places = 1
    return (fixed(metric['mean_a'] / divisor, places),
            fixed(metric['mean_b'] / divisor, places),
            signed(metric['effect'] / divisor, places),
            f"[{signed(metric['ci_low'] / divisor, places)}, {signed(metric['ci_high'] / divisor, places)}]")


def effort_result_table(
    glm: dict[str, Any],
    qwen: dict[str, Any],
    family: str,
    provenance: str,
) -> str:
    by_configuration = {
        "$g_{\\mathrm{GLM}}$": _effort_by_contrast(glm),
        "$g_{\\mathrm{Qwen}}$": _effort_by_contrast(qwen),
    }
    rendered: list[str] = []
    for panel, (metric, label) in enumerate((("tokens", r"Tokens [$\times 10^3$]"),
                                           ("api_calls", "Model API calls [calls]"),
                                           ("wall_seconds", "Run-time [s]"))):
        if panel:
            rendered.append(r"\addlinespace[8pt]")
        rendered.append(r"\multicolumn{7}{@{}l}{\textbf{" + label + r"}} \\")
        rendered.append(r"\addlinespace[2pt]")
        rendered.append(r"Configuration & Contrast & $|T^{(g)}_{ab}|$ & Mean $a$ & Mean $b$ & Difference & 95\,\% CI \\")
        rendered.append(r"\midrule")
        row_index = 0
        for configuration_index, (configuration, rows) in enumerate(by_configuration.items()):
            if configuration_index:
                rendered.append(r"\addlinespace[4pt]")
            for contrast in RQ_CONTRASTS[family]:
                row = rows[contrast]
                line = " & ".join([configuration, contrast_tex(contrast), str(row["n_tasks"]),
                                   *_effort_cell(row["metrics"][metric], metric)]) + r" \\"
                rendered.append((r"\rowcolor{black!6} " if row_index % 2 else "") + line)
                row_index += 1
    return (
        provenance
        + "\\begin{tabular}{@{}llrrrrr@{}}\n"
        + "  \\toprule\n"
        + "  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def recurrence_table(
    glm_rows: list[dict[str, str]],
    qwen_rows: list[dict[str, str]],
    provenance: str,
) -> str:
    glm = {row["contrast"]: row for row in glm_rows}
    qwen = {row["contrast"]: row for row in qwen_rows}
    rendered: list[str] = []
    for contrast in CONTRAST_ORDER:
        g, q = glm[contrast], qwen[contrast]
        same_sign = float(g["effect"]) * float(q["effect"]) > 0
        recurring = (
            same_sign
            and g["holm_reject_alpha_0_05"] == "True"
            and q["holm_reject_alpha_0_05"] == "True"
        )
        family = g["family"]
        rendered.append(
            (r"\rowcolor{black!6} " if len(rendered) % 2 else "")
            + " & ".join(
                [
                    family,
                    contrast_tex(contrast),
                    f"{signed(g['effect'], scale=100)} [{signed(g['ci_low'], scale=100)}, {signed(g['ci_high'], scale=100)}]",
                    p_value(g["p_value_holm"]),
                    f"{signed(q['effect'], scale=100)} [{signed(q['ci_low'], scale=100)}, {signed(q['ci_high'], scale=100)}]",
                    p_value(q["p_value_holm"]),
                    "yes" if recurring else "no",
                ]
            )
            + r" \\"
        )
    return (
        provenance
        + "\\begin{tabular}{@{}llrrrrc@{}}\n"
        + "  \\toprule\n"
        + "   & & \\multicolumn{2}{c}{$g_{\\mathrm{GLM}}$} & \\multicolumn{2}{c}{$g_{\\mathrm{Qwen}}$} & \\\\\n"
        + "  \\cmidrule(lr){3-4} \\cmidrule(lr){5-6}\n"
        + "  RQ & Contrast & $\\widehat\\Delta$ [95\\,\\% CI] & $p^{\\mathrm{Holm}}$ & "
          "$\\widehat\\Delta$ [95\\,\\% CI] & $p^{\\mathrm{Holm}}$ & Recurring \\\\\n"
        + "   & & [pp] & & [pp] & & evidence \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def delivered_only_table(
    glm_rows: list[dict[str, str]],
    qwen_rows: list[dict[str, str]],
    provenance: str,
) -> str:
    rendered: list[str] = []
    for configuration, rows in (
        ("$g_{\\mathrm{GLM}}$", glm_rows),
        ("$g_{\\mathrm{Qwen}}$", qwen_rows),
    ):
        for row in rows:
            rendered.append(
                (r"\rowcolor{black!6} " if len(rendered) % 2 else "")
                + " & ".join(
                    [
                        configuration,
                        row["family"],
                        contrast_tex(row["contrast"]),
                        row["n_tasks"],
                        signed(row["effect"], scale=100),
                        f"[{signed(row['ci_low'], scale=100)}, {signed(row['ci_high'], scale=100)}]",
                    ]
                )
                + r" \\"
            )
    return (
        provenance
        + "\\begin{tabular}{@{}lllrrr@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & RQ & Contrast & $|T^{(g)}_{ab}|$ & $\\widehat\\Delta$ & 95\\,\\% CI \\\\\n"
        + "   & & & & [pp] & [pp] \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def behaviour_table(
    glm: dict[str, dict[str, Any]],
    qwen: dict[str, dict[str, Any]],
    provenance: str,
) -> str:
    rendered: list[str] = []
    for configuration, summaries in (
        ("GLM", glm),
        ("Qwen", qwen),
    ):
        for cell in CELL_ORDER:
            row = summaries[cell]
            phases = row["phase_means"]
            activation = row["skill_activation_acting"]
            line = " & ".join(
                [
                    configuration,
                    cell,
                    str(row["acting_runs"]),
                    f"{phases['explore']:.1f}",
                    f"{phases['edit']:.1f}",
                    f"{phases['validate']:.1f}",
                    f"{phases['other']:.1f}",
                    f"{row['total_mean']:.1f}",
                    f"{row['wall_mean_seconds'] / 60:.1f}",
                    str(row["loops"]),
                    str(row["no_action"]),
                    str(row["timeout"]),
                    "---" if activation is None else f"{100 * activation:.0f}\\,\\%",
                ]
            ) + r" \\"
            rendered.append((r"\rowcolor{black!6} " if len(rendered) % 2 else "") + line)
    return (
        provenance
        + "\\begin{tabular}{@{}llrrrrrrrrrrr@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & Cell & Acting & \\multicolumn{5}{c}{Mean tool calls per acting run} & "
          "Run-time & Loops & No-action & Timeout & \\skillfile{} \\\\\n"
        + "  \\cmidrule(lr){4-8}\n"
        + "   & & runs & explore & edit & validate & other & total & [min] & runs & runs & runs & activation \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def activation_table(
    glm: dict[str, dict[str, int]],
    qwen: dict[str, dict[str, int]],
    provenance: str,
) -> str:
    rendered: list[str] = []
    for configuration, data in (("GLM", glm), ("Qwen", qwen)):
        for cell in ("K1s", "K2s"):
            row = data[cell]
            line = " & ".join(
                [
                    configuration,
                    cell,
                    f"{row['activated']}/{row['offered']}",
                    f"{100 * row['activated'] / row['offered']:.1f}\\,\\%",
                    str(row["read_and_quit"]),
                ]
            ) + r" \\"
            rendered.append((r"\rowcolor{black!6} " if len(rendered) % 2 else "") + line)
    return (
        provenance
        + "\\begin{tabular}{@{}llrrr@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & Cell & Activated/offered & Activation & Read-and-quit \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def loops_table(
    glm: list[dict[str, Any]],
    qwen: list[dict[str, Any]],
    provenance: str,
) -> str:
    rendered: list[str] = []
    for configuration, rows in (("GLM", glm), ("Qwen", qwen)):
        for row in rows:
            rendered.append(
                (r"\rowcolor{black!6} " if len(rendered) % 2 else "")
                + " & ".join(
                    [
                        configuration,
                        row["cell"],
                        row["task"].replace("_", "\\_"),
                        row["repetition"].replace("_", "\\_"),
                        str(row["calls"]),
                        row["outcome"].replace("_", " "),
                    ]
                )
                + r" \\"
            )
    if not rendered:
        rendered.append(r"None & --- & --- & --- & --- & --- \\")
    return (
        provenance
        + "\\begin{tabular}{@{}llp{5.4cm}rrl@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & Cell & Task & Repetition & Tool calls & Outcome \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def pilot_summary_table(glm: dict[str, Any], qwen: dict[str, Any], provenance: str) -> str:
    rows = []
    for label, summary in (("$g_{\\mathrm{GLM}}$", glm), ("$g_{\\mathrm{Qwen}}$", qwen)):
        role = ROLE_LABELS.get(summary["planning_role"])
        if role is None:
            raise ValueError(f"Unknown planning role: {summary['planning_role']}")
        timeout_count = int(summary["category_counts"].get("timeout", 0))
        rows.append(
            (r"\rowcolor{black!6} " if len(rows) % 2 else "")
            + " & ".join(
                [
                    label,
                    percent(float(summary["pass_at_1_first_10"])),
                    percent(float(summary["pass_at_1_all_20"])),
                    f"{float(summary['round_count_sample_sd']):.3f}",
                    f"{float(summary['mean_within_task_sample_variance']):.4f}",
                    f"{timeout_count}/{int(summary['planned_runs'])}",
                    role,
                ]
            )
            + r" \\"
        )
    return (
        provenance
        + "\\begin{tabular}{@{}lrrrrrp{3.5cm}@{}}\n"
        + "  \\toprule\n"
        + "  Agent configuration $g$ & pass@1, $n=10$ & pass@1, $n=20$ & $s_Y$, $n=20$ & "
          "$\\bar v_{\\mathrm{within}}$, $n=20$ & Timeouts & Pilot role \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rows)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def pilot_design_table(
    rows: list[dict[str, str]],
    chosen_task_count: int,
    chosen_repetitions: int,
    provenance: str,
) -> str:
    rendered = []
    chosen_found = False
    for row in rows:
        task_count = int(row["n_tasks"])
        repetitions = int(row["repetitions_per_cell"])
        values = [
            str(task_count),
            str(repetitions),
            str(int(row["planned_runs"])),
            fixed(row["estimated_hours"]),
            fixed(100 * float(row['planning_standard_error'])),
            fixed(100 * float(row['nominal_t_95_half_width'])),
        ]
        if task_count == chosen_task_count and repetitions == chosen_repetitions:
            values = [f"\\textbf{{{value}}}" for value in values]
            chosen_found = True
        rendered.append(
            (r"\rowcolor{black!6} " if len(rendered) % 2 else "")
            + " & ".join(values)
            + r" \\ "
        )
    if not chosen_found:
        raise ValueError("Chosen design is absent from design_precision.csv")
    return (
        provenance
        + "\\begin{tabular}{@{}rrrrrr@{}}\n"
        + "  \\toprule\n"
        + "  \\shortstack{Task-set size\\\\$|T|$} & \\shortstack{Repetition count\\\\$n$} & Runs & Server time [h] & "
          "\\shortstack{$\\mathrm{SE}_{\\mathrm{plan}}$\\\\{}[pp]} & \\shortstack{95\\,\\% half-width $h_{.95}$\\\\{}[pp]} \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def _outcome_counts(
    raw_rows: list[dict[str, str]],
    summary_rows: list[dict[str, str]],
) -> dict[str, dict[str, int]]:
    raw_to_label = {row["cell"]: row["cell_label"] for row in summary_rows}
    if set(raw_to_label.values()) != set(CELL_ORDER):
        raise ValueError("Cell summaries do not contain the six expected cell labels")

    counts = {
        label: {category: 0 for category in OUTCOME_CATEGORIES}
        for label in CELL_ORDER
    }
    measurable = {label: 0 for label in CELL_ORDER}
    for row in raw_rows:
        raw_cell = row["cell"]
        if raw_cell not in raw_to_label:
            raise ValueError(f"Raw-status mapping contains unknown cell: {raw_cell}")
        category = row["category"]
        if category not in OUTCOME_CATEGORIES:
            raise ValueError(f"Raw-status mapping contains unknown category: {category}")
        label = raw_to_label[raw_cell]
        counts[label][category] += 1
        if row["measurement_status"] == "measurable":
            measurable[label] += 1
        elif row["measurement_status"] != "not_measurable":
            raise ValueError(
                "Raw-status mapping contains unknown measurement status: "
                f"{row['measurement_status']}"
            )

    summary_by_label = {row["cell_label"]: row for row in summary_rows}
    for label in CELL_ORDER:
        planned = int(summary_by_label[label]["planned_runs"])
        if sum(counts[label].values()) != planned:
            raise ValueError(f"Outcome counts for {label} do not equal planned runs")
        if measurable[label] != int(summary_by_label[label]["measurable_runs"]):
            raise ValueError(f"Measurable count for {label} disagrees with cell summary")
        counts[label]["measurable"] = measurable[label]
    return counts


def main_outcome_counts_table(
    glm_raw_rows: list[dict[str, str]],
    qwen_raw_rows: list[dict[str, str]],
    glm_summary_rows: list[dict[str, str]],
    qwen_summary_rows: list[dict[str, str]],
    provenance: str,
) -> str:
    rendered: list[str] = []
    glm_counts = _outcome_counts(glm_raw_rows, glm_summary_rows)
    qwen_counts = _outcome_counts(qwen_raw_rows, qwen_summary_rows)
    row_index = 0
    for configuration, configuration_counts in (
        ("$g_{\\mathrm{GLM}}$", glm_counts),
        ("$g_{\\mathrm{Qwen}}$", qwen_counts),
    ):
        if rendered:
            rendered.append(r"\addlinespace[2pt]")
        for cell_label in CELL_ORDER:
            counts = configuration_counts[cell_label]
            other_nonmeasurable = counts["serving_error"] + counts["missing_artifact"]
            line = (
                " & ".join(
                    [
                        configuration,
                        cell_label,
                        str(counts["solved"]),
                        str(counts["failed_patch"]),
                        str(counts["empty_patch"]),
                        str(counts["no_action"]),
                        str(counts["timeout"]),
                        str(counts["evaluation_error"]),
                        str(other_nonmeasurable),
                        str(counts["measurable"]),
                    ]
                )
                + r" \\"
            )
            rendered.append((r"\rowcolor{black!6} " if row_index % 2 else "") + line)
            row_index += 1
    return (
        provenance
        + "\\begin{tabular}{@{}llrrrrrrrr@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & Cell & \\multicolumn{5}{c}{Measurable ($X$ defined)} & "
          "\\multicolumn{2}{c}{Not measurable ($X$ undefined)} & $M_{g,c}$ \\\\\n"
        + "  \\cmidrule(lr){3-7}\\cmidrule(lr){8-9}\n"
        + "  & & Solved & Failed patch & Empty patch & No-action & Timeout & "
          "Eval. error & Other error & Measurable total \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def contrast_sample_sizes_table(
    glm_rows: list[dict[str, str]],
    qwen_rows: list[dict[str, str]],
    provenance: str,
) -> str:
    glm_by_contrast = {row["contrast"]: row for row in glm_rows}
    qwen_by_contrast = {row["contrast"]: row for row in qwen_rows}
    if set(glm_by_contrast) != set(CONTRAST_ORDER) or set(qwen_by_contrast) != set(
        CONTRAST_ORDER
    ):
        raise ValueError("Contrast summaries do not contain the seven planned contrasts")

    rendered: list[str] = []
    for contrast in CONTRAST_ORDER:
        for configuration, row in (
            ("$g_{\\mathrm{GLM}}$", glm_by_contrast[contrast]),
            ("$g_{\\mathrm{Qwen}}$", qwen_by_contrast[contrast]),
        ):
            line = (
                " & ".join(
                    [
                        configuration,
                        contrast.replace("-", "$-$"),
                        row["family"],
                        row["planned_tasks"],
                        row["included_tasks"],
                        row["excluded_tasks"],
                        row["nonmeasurable_required_runs"],
                    ]
                )
                + r" \\"
            )
            rendered.append((r"\rowcolor{black!6} " if len(rendered) % 2 else "") + line)
    return (
        provenance
        + "\\begin{tabular}{@{}lllrrrr@{}}\n"
        + "  \\toprule\n"
        + "  Configuration & Contrast $a-b$ & Family & Planned $|T|$ & "
          "Complete $|T^{(g)}_{ab}|$ & Excluded tasks & Non-meas. runs \\\\\n"
        + "  \\midrule\n  "
        + "\n  ".join(rendered)
        + "\n  \\bottomrule\n\\end{tabular}\n"
    )


def write_pilot_tables(args: argparse.Namespace) -> None:
    glm_dir = args.glm_pilot_output.resolve()
    qwen_dir = args.qwen_pilot_output.resolve()
    config_path = args.glm_config.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    glm_summary_path = glm_dir / "summary.json"
    qwen_summary_path = qwen_dir / "summary.json"
    design_path = glm_dir / "design_precision.csv"
    config = load_json(config_path)

    command = (
        "thesis-results-assets pilot-tables --glm-pilot-output <GLM_OUTPUT> "
        "--qwen-pilot-output <QWEN_OUTPUT> --glm-config <GLM_CONFIG> "
        "--output-dir <OUTPUT_DIR>"
    )
    summary_provenance = source_comment(command, [glm_summary_path, qwen_summary_path])
    design_provenance = source_comment(command, [design_path, config_path])

    summary_tex = pilot_summary_table(
        load_json(glm_summary_path), load_json(qwen_summary_path), summary_provenance
    )
    design_tex = pilot_design_table(
        load_csv(design_path),
        int(config["chosen_task_count"]),
        int(config["chosen_repetitions"]),
        design_provenance,
    )
    (output_dir / "tab-pilot-summary-v2.tex").write_text(summary_tex, encoding="utf-8")
    (output_dir / "tab-pilot-design-v2.tex").write_text(design_tex, encoding="utf-8")


def write_pilot_figures(args: argparse.Namespace) -> None:
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    specifications = [
        (args.glm_pilot_output.resolve(), "vp-outcomes-glm.svg", "series-glm", "series-glm-fill"),
        (args.qwen_pilot_output.resolve(), "vp-outcomes-qwen.svg", "series-qwen", "series-qwen-fill"),
    ]
    for pilot_dir, filename, series, fill in specifications:
        output_path = output_dir / filename
        generate_matrix_svg(
            pilot_dir / "raw_status_mapping.csv",
            args.palette.resolve(),
            output_path,
            series,
            fill,
        )
        if args.render:
            render_svg(output_path)


def write_main_overview(args: argparse.Namespace) -> None:
    glm_dir = args.glm_main_output.resolve()
    qwen_dir = args.qwen_main_output.resolve()
    glm_raw_path = glm_dir / "raw_status_mapping.csv"
    qwen_raw_path = qwen_dir / "raw_status_mapping.csv"
    glm_summary_path = glm_dir / "cell_summaries.csv"
    qwen_summary_path = qwen_dir / "cell_summaries.csv"
    glm_contrasts_path = glm_dir / "contrast_sample_sizes.csv"
    qwen_contrasts_path = qwen_dir / "contrast_sample_sizes.csv"
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    command = (
        "thesis-results-assets main-overview --glm-main-output <GLM_OUTPUT> "
        "--qwen-main-output <QWEN_OUTPUT> --output-dir <OUTPUT_DIR>"
    )
    outcome_table = main_outcome_counts_table(
        load_csv(glm_raw_path),
        load_csv(qwen_raw_path),
        load_csv(glm_summary_path),
        load_csv(qwen_summary_path),
        source_comment(
            command,
            [glm_raw_path, qwen_raw_path, glm_summary_path, qwen_summary_path],
        ),
    )
    contrast_table = contrast_sample_sizes_table(
        load_csv(glm_contrasts_path),
        load_csv(qwen_contrasts_path),
        source_comment(command, [glm_contrasts_path, qwen_contrasts_path]),
    )
    (output_dir / "tab-main-overview-v2.tex").write_text(outcome_table, encoding="utf-8")
    (output_dir / "tab-main-contrast-sets-v2.tex").write_text(
        contrast_table, encoding="utf-8"
    )


def write_main_results(args: argparse.Namespace) -> None:
    glm_dir = args.glm_main_output.resolve()
    qwen_dir = args.qwen_main_output.resolve()
    output_dir = args.table_output_dir.resolve()
    figure_dir = args.figure_output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    figure_dir.mkdir(parents=True, exist_ok=True)

    glm_contrasts_path = glm_dir / "contrast_results.csv"
    qwen_contrasts_path = qwen_dir / "contrast_results.csv"
    glm_effort_path = glm_dir / "effort_bootstrap.json"
    qwen_effort_path = qwen_dir / "effort_bootstrap.json"
    glm_raw_path = glm_dir / "raw_status_mapping.csv"
    qwen_raw_path = qwen_dir / "raw_status_mapping.csv"
    glm_summary_path = glm_dir / "cell_summaries.csv"
    qwen_summary_path = qwen_dir / "cell_summaries.csv"
    glm_disagreement_path = glm_dir / "pairwise_disagreement.csv"
    qwen_disagreement_path = qwen_dir / "pairwise_disagreement.csv"
    glm_sensitivity_path = glm_dir / "delivered_only_sensitivity.csv"
    qwen_sensitivity_path = qwen_dir / "delivered_only_sensitivity.csv"

    glm_contrasts = load_csv(glm_contrasts_path)
    qwen_contrasts = load_csv(qwen_contrasts_path)
    glm_effort = load_json(glm_effort_path)
    qwen_effort = load_json(qwen_effort_path)
    command = (
        "thesis-results-assets main-results --glm-main-output <GLM_OUTPUT> "
        "--qwen-main-output <QWEN_OUTPUT> --palette <PALETTE> "
        "--table-output-dir <TABLE_DIR> --figure-output-dir <FIGURE_DIR>"
    )
    for family in RQ_CONTRASTS:
        pass_table = pass1_result_table(
            glm_contrasts,
            qwen_contrasts,
            family,
            source_comment(command, [glm_contrasts_path, qwen_contrasts_path]),
        )
        effort_table = effort_result_table(
            glm_effort,
            qwen_effort,
            family,
            source_comment(command, [glm_effort_path, qwen_effort_path]),
        )
        suffix = family.lower()
        (output_dir / f"tab-pass1-{suffix}.tex").write_text(pass_table, encoding="utf-8")
        (output_dir / f"tab-effort-{suffix}.tex").write_text(effort_table, encoding="utf-8")

    (output_dir / "tab-pass1-recurrence.tex").write_text(
        recurrence_table(
            glm_contrasts,
            qwen_contrasts,
            source_comment(command, [glm_contrasts_path, qwen_contrasts_path]),
        ),
        encoding="utf-8",
    )
    (output_dir / "tab-delivered-only-v2.tex").write_text(
        delivered_only_table(
            load_csv(glm_sensitivity_path),
            load_csv(qwen_sensitivity_path),
            source_comment(command, [glm_sensitivity_path, qwen_sensitivity_path]),
        ),
        encoding="utf-8",
    )

    glm_raw_rows = load_csv(glm_raw_path)
    qwen_raw_rows = load_csv(qwen_raw_path)
    glm_summary_rows = load_csv(glm_summary_path)
    qwen_summary_rows = load_csv(qwen_summary_path)
    glm_counts = _outcome_counts(glm_raw_rows, glm_summary_rows)
    qwen_counts = _outcome_counts(qwen_raw_rows, qwen_summary_rows)
    glm_labels = {row["cell"]: row["cell_label"] for row in glm_summary_rows}
    qwen_labels = {row["cell"]: row["cell_label"] for row in qwen_summary_rows}
    glm_behaviour, glm_loops, glm_activation = summarize_behaviour(glm_raw_rows, glm_labels)
    qwen_behaviour, qwen_loops, qwen_activation = summarize_behaviour(qwen_raw_rows, qwen_labels)
    behaviour_provenance = source_comment(command, [glm_raw_path, qwen_raw_path])
    (output_dir / "tab-behaviour-v2.tex").write_text(
        behaviour_table(glm_behaviour, qwen_behaviour, behaviour_provenance),
        encoding="utf-8",
    )
    (output_dir / "tab-activation-v2.tex").write_text(
        activation_table(glm_activation, qwen_activation, behaviour_provenance),
        encoding="utf-8",
    )
    (output_dir / "tab-loops-v2.tex").write_text(
        loops_table(glm_loops, qwen_loops, behaviour_provenance),
        encoding="utf-8",
    )
    palette_path = args.palette.resolve()
    outcome_path = figure_dir / "main-outcome-composition.svg"
    forest_path = figure_dir / "pass1-contrast-forest.svg"
    effort_forest_path = figure_dir / "mean-effort-contrast-forest.svg"
    disagreement_path = figure_dir / "pairwise-disagreement.svg"
    phase_path = figure_dir / "phase-profile-v2.svg"
    generate_outcome_composition_svg(
        glm_counts,
        qwen_counts,
        palette_path,
        outcome_path,
        f"{display_path(glm_raw_path)} and {display_path(qwen_raw_path)}",
    )
    generate_pass1_forest_svg(
        glm_contrasts,
        qwen_contrasts,
        palette_path,
        forest_path,
        f"{display_path(glm_contrasts_path)} and {display_path(qwen_contrasts_path)}",
    )
    generate_mean_effort_forest_svg(
        glm_effort, qwen_effort, palette_path, effort_forest_path,
        f"{display_path(glm_effort_path)} and {display_path(qwen_effort_path)}",
    )
    generate_pairwise_disagreement_svg(
        load_csv(glm_disagreement_path),
        load_csv(qwen_disagreement_path),
        palette_path,
        disagreement_path,
        f"{display_path(glm_disagreement_path)} and {display_path(qwen_disagreement_path)}",
    )
    generate_phase_profile_svg(
        glm_behaviour,
        qwen_behaviour,
        palette_path,
        phase_path,
        f"{display_path(glm_raw_path)} and {display_path(qwen_raw_path)}",
    )
    if args.render:
        for path in (outcome_path, forest_path, effort_forest_path, disagreement_path, phase_path):
            render_svg(path)


def write_material_categorization(args: argparse.Namespace) -> None:
    statements_path = args.statements.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    command = (
        "thesis-results-assets material-categorization --statements <STATEMENTS_CSV> "
        "--output-dir <OUTPUT_DIR>"
    )
    rendered = context_categorization_table(
        load_csv(statements_path), source_comment(command, [statements_path])
    )
    (output_dir / "tab-context-categorization.tex").write_text(
        rendered, encoding="utf-8"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate thesis tables and figures from Phase-B outputs."
    )
    subparsers = parser.add_subparsers(dest="asset", required=True)
    pilot = subparsers.add_parser("pilot-tables", help="Generate variance-pilot tables.")
    pilot.add_argument("--glm-pilot-output", type=Path, required=True)
    pilot.add_argument("--qwen-pilot-output", type=Path, required=True)
    pilot.add_argument("--glm-config", type=Path, required=True)
    pilot.add_argument("--output-dir", type=Path, required=True)
    pilot.set_defaults(handler=write_pilot_tables)
    figures = subparsers.add_parser("pilot-figures", help="Generate variance-pilot outcome matrices.")
    figures.add_argument("--glm-pilot-output", type=Path, required=True)
    figures.add_argument("--qwen-pilot-output", type=Path, required=True)
    figures.add_argument("--palette", type=Path, required=True)
    figures.add_argument("--output-dir", type=Path, required=True)
    figures.add_argument("--render", action="store_true", help="Also render PDF and @2x PNG with rsvg-convert.")
    figures.set_defaults(handler=write_pilot_figures)
    overview = subparsers.add_parser(
        "main-overview",
        help="Generate main-run outcome-count and complete-contrast-set tables.",
    )
    overview.add_argument("--glm-main-output", type=Path, required=True)
    overview.add_argument("--qwen-main-output", type=Path, required=True)
    overview.add_argument("--output-dir", type=Path, required=True)
    overview.set_defaults(handler=write_main_overview)
    results = subparsers.add_parser(
        "main-results",
        help="Generate RQ tables and audited main-run figures.",
    )
    results.add_argument("--glm-main-output", type=Path, required=True)
    results.add_argument("--qwen-main-output", type=Path, required=True)
    results.add_argument("--palette", type=Path, required=True)
    results.add_argument("--table-output-dir", type=Path, required=True)
    results.add_argument("--figure-output-dir", type=Path, required=True)
    results.add_argument("--render", action="store_true")
    results.set_defaults(handler=write_main_results)
    material = subparsers.add_parser(
        "material-categorization",
        help="Generate repository-level context-statement categorization table.",
    )
    material.add_argument("--statements", type=Path, required=True)
    material.add_argument("--output-dir", type=Path, required=True)
    material.set_defaults(handler=write_material_categorization)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.handler(args)


if __name__ == "__main__":
    main()
